/**
 * Comprehensive list of French stocks (CAC 40 + SBF 120 majors) and indices
 * available for tracking on the Marché page.
 */

export type MarketCategory = "Action" | "Indice";

export interface MarketInstrument {
  ticker: string;
  name: string;
  sector: string;
  category: MarketCategory;
}

export const FRENCH_INSTRUMENTS: MarketInstrument[] = [
  // ──────────────── INDICES ────────────────
  {
    ticker: "^FCHI",
    name: "CAC 40",
    sector: "Indice France",
    category: "Indice",
  },
  {
    ticker: "^SBF120",
    name: "SBF 120",
    sector: "Indice France",
    category: "Indice",
  },
  {
    ticker: "^STOXX50E",
    name: "Euro Stoxx 50",
    sector: "Indice Europe",
    category: "Indice",
  },
  {
    ticker: "^STOXX",
    name: "Stoxx Europe 600",
    sector: "Indice Europe",
    category: "Indice",
  },
  {
    ticker: "^GSPC",
    name: "S&P 500",
    sector: "Indice USA",
    category: "Indice",
  },
  {
    ticker: "^DJI",
    name: "Dow Jones",
    sector: "Indice USA",
    category: "Indice",
  },
  {
    ticker: "^IXIC",
    name: "Nasdaq Composite",
    sector: "Indice USA",
    category: "Indice",
  },
  {
    ticker: "^GDAXI",
    name: "DAX 40",
    sector: "Indice Allemagne",
    category: "Indice",
  },
  {
    ticker: "^FTSE",
    name: "FTSE 100",
    sector: "Indice UK",
    category: "Indice",
  },
  {
    ticker: "^N225",
    name: "Nikkei 225",
    sector: "Indice Japon",
    category: "Indice",
  },

  // ──────────────── CAC 40 ────────────────
  {
    ticker: "AI.PA",
    name: "Air Liquide",
    sector: "Chimie",
    category: "Action",
  },
  {
    ticker: "AIR.PA",
    name: "Airbus",
    sector: "Aéronautique",
    category: "Action",
  },
  { ticker: "ALO.PA", name: "Alstom", sector: "Industrie", category: "Action" },
  {
    ticker: "MT.AS",
    name: "ArcelorMittal",
    sector: "Acier",
    category: "Action",
  },
  { ticker: "CS.PA", name: "AXA", sector: "Assurance", category: "Action" },
  {
    ticker: "BNP.PA",
    name: "BNP Paribas",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "EN.PA",
    name: "Bouygues",
    sector: "Construction",
    category: "Action",
  },
  {
    ticker: "CAP.PA",
    name: "Capgemini",
    sector: "IT Services",
    category: "Action",
  },
  {
    ticker: "CA.PA",
    name: "Carrefour",
    sector: "Distribution",
    category: "Action",
  },
  {
    ticker: "ACA.PA",
    name: "Crédit Agricole",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "BN.PA",
    name: "Danone",
    sector: "Alimentaire",
    category: "Action",
  },
  {
    ticker: "DSY.PA",
    name: "Dassault Systèmes",
    sector: "Logiciel",
    category: "Action",
  },
  { ticker: "ENGI.PA", name: "Engie", sector: "Énergie", category: "Action" },
  {
    ticker: "EL.PA",
    name: "EssilorLuxottica",
    sector: "Optique",
    category: "Action",
  },
  {
    ticker: "ERF.PA",
    name: "Eurofins Scientific",
    sector: "Biotechnologie",
    category: "Action",
  },
  { ticker: "RMS.PA", name: "Hermès", sector: "Luxe", category: "Action" },
  { ticker: "KER.PA", name: "Kering", sector: "Luxe", category: "Action" },
  {
    ticker: "LR.PA",
    name: "Legrand",
    sector: "Électrique",
    category: "Action",
  },
  {
    ticker: "OR.PA",
    name: "L'Oréal",
    sector: "Cosmétiques",
    category: "Action",
  },
  { ticker: "MC.PA", name: "LVMH", sector: "Luxe", category: "Action" },
  {
    ticker: "ML.PA",
    name: "Michelin",
    sector: "Pneumatiques",
    category: "Action",
  },
  { ticker: "ORA.PA", name: "Orange", sector: "Télécoms", category: "Action" },
  {
    ticker: "RI.PA",
    name: "Pernod Ricard",
    sector: "Spiritueux",
    category: "Action",
  },
  {
    ticker: "PUB.PA",
    name: "Publicis Groupe",
    sector: "Publicité",
    category: "Action",
  },
  {
    ticker: "RNO.PA",
    name: "Renault",
    sector: "Automobile",
    category: "Action",
  },
  {
    ticker: "SAF.PA",
    name: "Safran",
    sector: "Aéronautique",
    category: "Action",
  },
  {
    ticker: "SGO.PA",
    name: "Saint-Gobain",
    sector: "Matériaux",
    category: "Action",
  },
  { ticker: "SAN.PA", name: "Sanofi", sector: "Pharma", category: "Action" },
  {
    ticker: "SU.PA",
    name: "Schneider Electric",
    sector: "Électrique",
    category: "Action",
  },
  {
    ticker: "GLE.PA",
    name: "Société Générale",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "STLAM.MI",
    name: "Stellantis",
    sector: "Automobile",
    category: "Action",
  },
  {
    ticker: "STMPA.PA",
    name: "STMicroelectronics",
    sector: "Semi-conducteurs",
    category: "Action",
  },
  {
    ticker: "TEP.PA",
    name: "Teleperformance",
    sector: "Services",
    category: "Action",
  },
  { ticker: "HO.PA", name: "Thales", sector: "Défense", category: "Action" },
  {
    ticker: "TTE.PA",
    name: "TotalEnergies",
    sector: "Énergie",
    category: "Action",
  },
  {
    ticker: "URW.AS",
    name: "Unibail-Rodamco",
    sector: "Immobilier",
    category: "Action",
  },
  {
    ticker: "VIE.PA",
    name: "Veolia",
    sector: "Environnement",
    category: "Action",
  },
  {
    ticker: "DG.PA",
    name: "Vinci",
    sector: "Construction",
    category: "Action",
  },
  { ticker: "VIV.PA", name: "Vivendi", sector: "Médias", category: "Action" },

  // ──────────────── ACTIONS FRANÇAISES HORS CAC 40 ────────────────
  { ticker: "ATO.PA", name: "Atos", sector: "IT Services", category: "Action" },
  { ticker: "BB.PA", name: "Bic", sector: "Consommation", category: "Action" },
  {
    ticker: "BIM.PA",
    name: "bioMérieux",
    sector: "Biotechnologie",
    category: "Action",
  },
  {
    ticker: "BOL.PA",
    name: "Bolloré",
    sector: "Transport",
    category: "Action",
  },
  { ticker: "CGG.PA", name: "CGG", sector: "Géosciences", category: "Action" },
  {
    ticker: "CO.PA",
    name: "Casino",
    sector: "Distribution",
    category: "Action",
  },
  {
    ticker: "COV.PA",
    name: "Covivio",
    sector: "Immobilier",
    category: "Action",
  },
  {
    ticker: "DBG.PA",
    name: "Derichebourg",
    sector: "Environnement",
    category: "Action",
  },
  { ticker: "EDN.PA", name: "Edenred", sector: "Services", category: "Action" },
  { ticker: "EDF.PA", name: "EDF", sector: "Énergie", category: "Action" },
  {
    ticker: "FGR.PA",
    name: "Eiffage",
    sector: "Construction",
    category: "Action",
  },
  { ticker: "ELE.PA", name: "Elis", sector: "Services", category: "Action" },
  {
    ticker: "ETL.PA",
    name: "Eutelsat",
    sector: "Télécoms",
    category: "Action",
  },
  {
    ticker: "FDJ.PA",
    name: "La Française des Jeux",
    sector: "Jeux",
    category: "Action",
  },
  {
    ticker: "GET.PA",
    name: "Getlink",
    sector: "Transport",
    category: "Action",
  },
  { ticker: "GTT.PA", name: "GTT", sector: "Énergie", category: "Action" },
  {
    ticker: "ICAD.PA",
    name: "Icade",
    sector: "Immobilier",
    category: "Action",
  },
  {
    ticker: "ILD.PA",
    name: "ID Logistics",
    sector: "Logistique",
    category: "Action",
  },
  { ticker: "IPS.PA", name: "Ipsen", sector: "Pharma", category: "Action" },
  {
    ticker: "ITP.PA",
    name: "Interparfums",
    sector: "Cosmétiques",
    category: "Action",
  },
  { ticker: "MMB.PA", name: "Lagardère", sector: "Médias", category: "Action" },
  {
    ticker: "MAU.PA",
    name: "Maurel & Prom",
    sector: "Pétrole",
    category: "Action",
  },
  {
    ticker: "MMT.PA",
    name: "Métropole TV (M6)",
    sector: "Médias",
    category: "Action",
  },
  { ticker: "NEX.PA", name: "Nexans", sector: "Câbles", category: "Action" },
  { ticker: "NK.PA", name: "Imerys", sector: "Minéraux", category: "Action" },
  {
    ticker: "ODET.PA",
    name: "Compagnie de l'Odet",
    sector: "Holding",
    category: "Action",
  },
  {
    ticker: "PAT.PA",
    name: "Patrimoine et Commerce",
    sector: "Immobilier",
    category: "Action",
  },
  {
    ticker: "RCO.PA",
    name: "Rémy Cointreau",
    sector: "Spiritueux",
    category: "Action",
  },
  {
    ticker: "RXL.PA",
    name: "Rexel",
    sector: "Distribution",
    category: "Action",
  },
  { ticker: "RBT.PA", name: "Robertet", sector: "Chimie", category: "Action" },
  { ticker: "RUI.PA", name: "Rubis", sector: "Énergie", category: "Action" },
  { ticker: "SCR.PA", name: "SCOR", sector: "Réassurance", category: "Action" },
  {
    ticker: "SEB.PA",
    name: "SEB",
    sector: "Électroménager",
    category: "Action",
  },
  { ticker: "SK.PA", name: "SEB", sector: "Équipement", category: "Action" },
  {
    ticker: "SOI.PA",
    name: "Soitec",
    sector: "Semi-conducteurs",
    category: "Action",
  },
  {
    ticker: "SPB.PA",
    name: "Sopra Steria",
    sector: "IT Services",
    category: "Action",
  },
  {
    ticker: "SW.PA",
    name: "Sodexo",
    sector: "Restauration",
    category: "Action",
  },
  { ticker: "TFI.PA", name: "TF1", sector: "Médias", category: "Action" },
  {
    ticker: "UBI.PA",
    name: "Ubisoft",
    sector: "Jeux Vidéo",
    category: "Action",
  },
  { ticker: "VAL.PA", name: "Valeo", sector: "Automobile", category: "Action" },
  {
    ticker: "VLA.PA",
    name: "Valneva",
    sector: "Biotechnologie",
    category: "Action",
  },
  {
    ticker: "WLN.PA",
    name: "Worldline",
    sector: "Paiements",
    category: "Action",
  },

  // ──────────────── ACTIONS EUROPÉENNES ÉLIGIBLES PEA ────────────────
  // Pays-Bas
  {
    ticker: "ASML.AS",
    name: "ASML Holding",
    sector: "Semi-conducteurs",
    category: "Action",
  },
  {
    ticker: "PHIA.AS",
    name: "Philips",
    sector: "Santé / Tech",
    category: "Action",
  },
  {
    ticker: "AD.AS",
    name: "Ahold Delhaize",
    sector: "Distribution",
    category: "Action",
  },
  {
    ticker: "INGA.AS",
    name: "ING Group",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "UNA.AS",
    name: "Unilever",
    sector: "Consommation",
    category: "Action",
  },
  {
    ticker: "WKL.AS",
    name: "Wolters Kluwer",
    sector: "Édition / Tech",
    category: "Action",
  },
  // Allemagne
  {
    ticker: "SAP.DE",
    name: "SAP",
    sector: "Logiciel",
    category: "Action",
  },
  {
    ticker: "SIE.DE",
    name: "Siemens",
    sector: "Industrie",
    category: "Action",
  },
  {
    ticker: "ALV.DE",
    name: "Allianz",
    sector: "Assurance",
    category: "Action",
  },
  {
    ticker: "ADS.DE",
    name: "Adidas",
    sector: "Sport",
    category: "Action",
  },
  {
    ticker: "BAS.DE",
    name: "BASF",
    sector: "Chimie",
    category: "Action",
  },
  {
    ticker: "DTE.DE",
    name: "Deutsche Telekom",
    sector: "Télécoms",
    category: "Action",
  },
  {
    ticker: "MUV2.DE",
    name: "Munich Re",
    sector: "Réassurance",
    category: "Action",
  },
  {
    ticker: "BMW.DE",
    name: "BMW",
    sector: "Automobile",
    category: "Action",
  },
  {
    ticker: "VOW3.DE",
    name: "Volkswagen",
    sector: "Automobile",
    category: "Action",
  },
  {
    ticker: "MRK.DE",
    name: "Merck KGaA",
    sector: "Pharma",
    category: "Action",
  },
  {
    ticker: "IFX.DE",
    name: "Infineon",
    sector: "Semi-conducteurs",
    category: "Action",
  },
  {
    ticker: "RHM.DE",
    name: "Rheinmetall",
    sector: "Défense",
    category: "Action",
  },
  // Italie
  {
    ticker: "ENEL.MI",
    name: "Enel",
    sector: "Énergie",
    category: "Action",
  },
  {
    ticker: "ISP.MI",
    name: "Intesa Sanpaolo",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "UCG.MI",
    name: "UniCredit",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "ENI.MI",
    name: "ENI",
    sector: "Pétrole",
    category: "Action",
  },
  {
    ticker: "RACE.MI",
    name: "Ferrari",
    sector: "Automobile / Luxe",
    category: "Action",
  },
  // Espagne
  {
    ticker: "SAN.MC",
    name: "Banco Santander",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "IBE.MC",
    name: "Iberdrola",
    sector: "Énergie",
    category: "Action",
  },
  {
    ticker: "ITX.MC",
    name: "Inditex (Zara)",
    sector: "Textile",
    category: "Action",
  },
  {
    ticker: "TEF.MC",
    name: "Telefónica",
    sector: "Télécoms",
    category: "Action",
  },
  // Belgique
  {
    ticker: "ABI.BR",
    name: "AB InBev",
    sector: "Brasserie",
    category: "Action",
  },
  {
    ticker: "KBC.BR",
    name: "KBC Group",
    sector: "Banque",
    category: "Action",
  },
  {
    ticker: "UCB.BR",
    name: "UCB",
    sector: "Pharma",
    category: "Action",
  },
  // Finlande / Irlande / Portugal
  {
    ticker: "NOKIA.HE",
    name: "Nokia",
    sector: "Télécoms / Tech",
    category: "Action",
  },
  {
    ticker: "CRH.L",
    name: "CRH",
    sector: "Matériaux",
    category: "Action",
  },
  {
    ticker: "GALP.LS",
    name: "Galp Energia",
    sector: "Énergie",
    category: "Action",
  },

  // ──────────────── ACTIONS FRANÇAISES SUPPLÉMENTAIRES ────────────────
  {
    ticker: "AM.PA",
    name: "Dassault Aviation",
    sector: "Aéronautique",
    category: "Action",
  },
  {
    ticker: "BVI.PA",
    name: "Bureau Veritas",
    sector: "Services",
    category: "Action",
  },
  {
    ticker: "AKE.PA",
    name: "Arkema",
    sector: "Chimie",
    category: "Action",
  },
  {
    ticker: "ERA.PA",
    name: "Eramet",
    sector: "Mines",
    category: "Action",
  },
  {
    ticker: "VCT.PA",
    name: "Vicat",
    sector: "Matériaux",
    category: "Action",
  },
  {
    ticker: "SMCP.PA",
    name: "SMCP (Sandro / Maje)",
    sector: "Mode",
    category: "Action",
  },
  {
    ticker: "OVH.PA",
    name: "OVHcloud",
    sector: "Cloud / Tech",
    category: "Action",
  },
  {
    ticker: "ALHYG.PA",
    name: "Hydrogen Refueling Solutions",
    sector: "Hydrogène",
    category: "Action",
  },
  {
    ticker: "NEOEN.PA",
    name: "Neoen",
    sector: "Énergies renouvelables",
    category: "Action",
  },
  {
    ticker: "ALFEN.PA",
    name: "Alfen",
    sector: "Énergie / Tech",
    category: "Action",
  },
];
