import { Asset, Transaction } from "./calculations";

export const MOCK_ASSETS: Asset[] = [
  {
    id: "1",
    ticker: "AI.PA",
    name: "Air Liquide",
    sector: "Chimie",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "2",
    ticker: "BNP.PA",
    name: "BNP Paribas",
    sector: "Banque",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "3",
    ticker: "MC.PA",
    name: "LVMH",
    sector: "Luxe",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "4",
    ticker: "TTE.PA",
    name: "TotalEnergies",
    sector: "Énergie",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "5",
    ticker: "SAN.PA",
    name: "Sanofi",
    sector: "Santé",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "6",
    ticker: "OR.PA",
    name: "L'Oréal",
    sector: "Cosmétique",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "7",
    ticker: "SU.PA",
    name: "Schneider Electric",
    sector: "Industrie",
    currency: "EUR",
    created_at: "",
  },
  {
    id: "8",
    ticker: "CAP.PA",
    name: "Capgemini",
    sector: "Tech",
    currency: "EUR",
    created_at: "",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    ticker: "AI.PA",
    type: "Achat",
    date: "2024-03-15",
    quantity: 10,
    unit_price: 178.5,
    total_amount: 1785.0,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "2",
    ticker: "AI.PA",
    type: "Achat",
    date: "2024-06-20",
    quantity: 5,
    unit_price: 165.3,
    total_amount: 826.5,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "3",
    ticker: "AI.PA",
    type: "Dividende",
    date: "2024-07-10",
    quantity: 0,
    unit_price: 0,
    total_amount: 45.0,
    fees: 0,
    created_at: "",
  },
  {
    id: "4",
    ticker: "BNP.PA",
    type: "Achat",
    date: "2024-02-10",
    quantity: 20,
    unit_price: 58.2,
    total_amount: 1164.0,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "5",
    ticker: "BNP.PA",
    type: "Dividende",
    date: "2024-05-15",
    quantity: 0,
    unit_price: 0,
    total_amount: 84.0,
    fees: 0,
    created_at: "",
  },
  {
    id: "6",
    ticker: "MC.PA",
    type: "Achat",
    date: "2024-01-20",
    quantity: 3,
    unit_price: 725.0,
    total_amount: 2175.0,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "7",
    ticker: "MC.PA",
    type: "Dividende",
    date: "2024-04-20",
    quantity: 0,
    unit_price: 0,
    total_amount: 42.0,
    fees: 0,
    created_at: "",
  },
  {
    id: "8",
    ticker: "TTE.PA",
    type: "Achat",
    date: "2024-04-05",
    quantity: 25,
    unit_price: 62.8,
    total_amount: 1570.0,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "9",
    ticker: "TTE.PA",
    type: "Dividende",
    date: "2024-06-25",
    quantity: 0,
    unit_price: 0,
    total_amount: 47.5,
    fees: 0,
    created_at: "",
  },
  {
    id: "10",
    ticker: "TTE.PA",
    type: "Dividende",
    date: "2024-09-25",
    quantity: 0,
    unit_price: 0,
    total_amount: 47.5,
    fees: 0,
    created_at: "",
  },
  {
    id: "11",
    ticker: "SAN.PA",
    type: "Achat",
    date: "2024-05-12",
    quantity: 15,
    unit_price: 91.5,
    total_amount: 1372.5,
    fees: 1.99,
    created_at: "",
  },
  {
    id: "12",
    ticker: "SAN.PA",
    type: "Dividende",
    date: "2024-08-15",
    quantity: 0,
    unit_price: 0,
    total_amount: 57.0,
    fees: 0,
    created_at: "",
  },
  {
    id: "13",
    ticker: "CAP.PA",
    type: "Achat",
    date: "2024-07-01",
    quantity: 8,
    unit_price: 195.0,
    total_amount: 1560.0,
    fees: 1.99,
    created_at: "",
  },
];

// Prix simulés pour le mode sans API
export const MOCK_PRICES: Record<
  string,
  { price: number; change: number; changePercent: number }
> = {
  "AI.PA": { price: 182.4, change: 2.1, changePercent: 1.16 },
  "BNP.PA": { price: 61.85, change: -1.42, changePercent: -2.24 },
  "MC.PA": { price: 698.5, change: -8.3, changePercent: -1.17 },
  "TTE.PA": { price: 65.92, change: 0.78, changePercent: 1.2 },
  "SAN.PA": { price: 94.2, change: 1.05, changePercent: 1.13 },
  "OR.PA": { price: 412.3, change: -3.5, changePercent: -0.84 },
  "SU.PA": { price: 218.6, change: 4.2, changePercent: 1.96 },
  "CAP.PA": { price: 188.7, change: -5.4, changePercent: -2.78 },
};
