-- VERSION SIMPLIFIEE (Mono-utilisateur)
-- Suppression de la table existante pour repartir au propre
DROP TABLE IF EXISTS public.favorites;

CREATE TABLE public.favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Désactivation du RLS car c'est une app perso sans auth
ALTER TABLE public.favorites DISABLE ROW LEVEL SECURITY;
